version = 0.1
[DEV]
[DEV.deploy]
[DEV.deploy.parameters]
stack_name = "push-notification-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iu6chgguwuus"
s3_prefix = "push-notification-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBName=\"InboxRecordDBTable\" SNSTopicName=\"MPF\""

[Dev]
[Dev.deploy]
[Dev.deploy.parameters]
stack_name = "push-notification-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iu6chgguwuus"
s3_prefix = "push-notification-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBName=\"InboxRecordDBTable\" SNSTopicName=\"MPF\""

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "push-notification-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11y3xp1to0c3v"
s3_prefix = "push-notification-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBName=\"InboxRecordDBTable\""

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "push-notification-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iu6chgguwuus"
s3_prefix = "push-notification-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBName=\"InboxRecordDBTable\" SNSTopicName=\"MPF\""

[UAT]
[UAT.deploy]
[UAT.deploy.parameters]
stack_name = "push-notification-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iu6chgguwuus"
s3_prefix = "push-notification-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBName=\"InboxRecordDBTable\" SNSTopicName=\"MPF\""
